build:
  binary: supervisord
  goos:
    - linux
    #- darwin
  goarch:
    - amd64
  ldflags:
  - "-linkmode external -extldflags -static"
archive:
  format: binary
snapshot:
  name_template: "{{.Commit}}"
